language: java

before_install:
 - sudo apt-get -y install build-essential git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev libmagic-dev libhdf5-serial-dev libxml2 libxml2-dev automake python-pip python-numpy
 - export PATH="$HOME/.linuxbrew/bin:$PATH"
 - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
 - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
 - echo -ne '\n' | ruby -e "$(wget -O- https://raw.github.com/Homebrew/linuxbrew/go/install)"
 - brew tap homebrew/science
 - brew install cmake > cmake.log

install:
    - brew install -v --quieter opencv.rb
    - export PYTHONPATH="$HOME/.linuxbrew/Cellar/opencv/2.4.9/lib/python2.7/site-packages"
script:
    - python -c "import cv"
