language: ruby
install:
 - jdk_switcher use oraclejdk7
 # Warning: Setting DYLD_* vars can break dynamic linking.
 - unset DYLD_LIBRARY_PATH
 # Warning: You have a non-Homebrew 'pkg-config' in your PATH
 - sudo rm -f /usr/bin/pkg-config
 # Warning: "config" scripts exist outside your system or Homebrew directories.
 - sudo rm -f /usr/local/clang-3.4/bin/llvm-config

   # Install gcc-4.9 system wide[Default is gcc-4.6]
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq #&& sudo apt-get upgrade -y
 - sudo apt-get install -y libyajl-dev libxml2-dev libxqilla-dev
 - sudo apt-get install -y libstdc++-4.9-dev
 - sudo apt-get install -y g++-4.9 gfortran-4.9
 - sudo apt-get install -y libblas-dev liblapack-dev python-pip cmake openjdk-7-jdk jblas
   
 - sudo pip install jinja2
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
 - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-4.9 90
 - cd ..
 - git clone https://github.com/Homebrew/linuxbrew.git
 - PATH=$PWD/linuxbrew/bin:$PATH
 - sudo apt-get install  libbz2-dev cdbs libarpack2-dev libatlas-base-dev libblas-dev libglpk-dev libhdf5-serial-dev zlib1g-dev libxml2-dev libreadline6-dev libreadline-dev libsnappy-dev liblzo2-dev liblzma-dev liblapack-dev libeigen3-dev gdb cmake python-jinja2

  # Symlink gcc, gfortran
 - ln -s $(which gcc) $PWD/linuxbrew/bin/gcc-$(gcc -dumpversion |cut -d. -f1,2)
 - ln -s $(which g++) $PWD/linuxbrew/bin/g++-$(g++ -dumpversion |cut -d. -f1,2)
 - ln -s $(which gfortran) $PWD/linuxbrew/bin/gfortran-$(gfortran -dumpversion |cut -d. -f1,2)
 - mkdir -p $PWD/linuxbrew/Cellar/gcc/4.9.2_1
 - mkdir -p $PWD/linuxbrew/Cellar/cmake/3.1.1_1
 - touch $PWD/linuxbrew/Cellar/gcc/4.9.2_1/INSTALL_RECEIPT
 - touch $PWD/linuxbrew/Cellar/cmake/3.1.1_1/INSTALL_RECEIPT

 # Install pkg-config[See: https://github.com/Homebrew/brewer/pull/1664#issuecomment-69259072]
 - brew install pkg-config

 - mkdir -p linuxbrew/Library/Taps/homebrew
 - ls -1 linuxbrew/Cellar/
 - brew tap homebrew/homebrew-science
 - mv brewer linuxbrew/Library/Taps/homebrew/
 - cd linuxbrew/Library/Taps/homebrew/brewer
 - brew tap --repair
 - brew list
 # Incorrect file permissions: chmod 644
 - chmod 644 *.rb
script:
    #- brew install shogun.rb --with-lua-modular

    - bash travisCI/travis.sh

notifications:
 email: false
