language: java

before_install:
 - sudo apt-get install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev
 - export PATH="$HOME/.linuxbrew/bin:$PATH"
 - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
 - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
 - ruby -e "$(wget -O- https://raw.github.com/Homebrew/linuxbrew/go/install)"
install:
 - brew install sratoolkit.rb
script:
 - fastq-dump
